apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-deployment
  labels:
    app: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: api-container
          image: mjajod2/flask:v4
          imagePullPolicy: Always
          command: ["python3"]
          args: ["hello.py"]
          env:
          - name: PASSWORD
            value: "admin"
          - name: DBNAME
            value: "gcp-agrofa"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
