apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: serviceaccount-2
  namespace: default
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io
