apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  labels:
    service: web-frontend
spec:
  selector:
    app: web-frontend
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 80
